# Generated by Django 3.1.4 on 2020-12-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('fechaPublicacion', models.DateField()),
                ('categoria', models.CharField(max_length=30)),
                ('palabraClave', models.CharField(max_length=30)),
                ('recurso', models.CharField(max_length=500)),
            ],
        ),
    ]
