# Generated by Django 3.1.4 on 2020-12-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchAll', '0002_video_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('videos', models.ManyToManyField(to='watchAll.Video')),
            ],
        ),
    ]
