# Generated by Django 3.1.4 on 2021-01-08 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('fechaNacimiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha nacimiento')),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenimo'), ('Masculino', 'Masculino')], default='Femenino', max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('token', models.UUIDField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
