# Generated by Django 3.1.4 on 2021-01-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='token',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
