# Generated by Django 3.1.4 on 2020-12-20 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_auto_20201218_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='apellido',
            field=models.CharField(max_length=30, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fechaNacimiento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='sexo',
            field=models.CharField(default='Femenino', max_length=10),
        ),
    ]
