# Generated by Django 3.1.4 on 2021-01-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0006_auto_20210104_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
