# Generated by Django 3.1.4 on 2021-01-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0007_auto_20210106_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='token',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
